# config/doctrine/schema.yml
Earthquake:
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer
      notnull: true
      unique: true
      primary: true
    magnitude:
      type: float
    link:
      type: string(400)
    description:
      type: string(255)
    latitude:
      type: float
    longitude:
      type: float
    time_of_quake:
      type: datetime
    depth:
      type: float

Report:
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer
      notnull: true
      unique: true
      primary: true
    earthquake_id:
      type: integer
      notnull: true

    felt:
      type: boolean
      default: true
      notnull: true
    other_felt:
      type: enum
      values: ['NONE','SOME','MOST','EVERYONE']
      notnull: true
      default: NONE
    asleep:
      type: enum
      values: ['NO','SLEPT_THROUGH','WOKE_UP']
      notnull: true
      default: NO
    situation:
      type: enum
      values: ['INSIDE','OUTSIDE','STOPPED_VEHICLE','MOVING_VEHICLE','OTHER']
      notnull: true
      default: INSIDE
    situation_other:
      type: string(255)
    motion:
      type: enum
      values: ['NOT_FELT','WEAK','MILD','MODERATE','STRONG','VIOLENT']
      notnull: true
      default: NOT_FELT
    duration:
      type: integer
    reaction:
      type: enum
      values: ['NONE','LITTLE','EXCITEMENT','SOMEWHAT_FRIGHTENED','VERY_FRIGHTENED','EXTREMELY_FRIGHTENED']
      notnull: true
      default: NONE
    response:
      type: enum
      values: ['NONE','DOORWAY','DUCKED','RAN_OUTSIDE','OTHER']
      notnull: true
      default: TOOK_NO_ACTION
    stand:
      type: boolean
      notnull: true
      default: false
    sway:
      type: enum
      values: ['NO','SLIGHT','VIOLENT']
      notnull: true
      default: NO
    creak:
      type: enum
      values: ['NO','SLIGHT','LOUD']
      notnull: true
      default: NO
    shelf:
      type: enum
      values: ['NO','RATTLED_SLIGHTLY','RATTLED_LOUDLY','FEW_TOPPLED','MANY_FELL','MOST_FELL']
      notnull: true
      default: NO
    picture:
      type: enum
      values: ['NO','NONE_FELL','SOME_FELL']
      notnull: true
      default: NO
    furniture:
      type: boolean
      notnull: true
      default: false
    heavy_appliance:
      type: enum
      values: ['NO','SOME_CONTENTS_FELL','SHIFTED_CM','SHIFTED_M','OVERTURNED']
      notnull: true
      default: NO
    walls:
      type: enum
      values: ['NO','SOME_CRACKED','PARTIAL_FALL','COMPLETE_FALL']
      notnull: true
      default: NO
    reporter_name:
      type: string(255)
    contact_phone:
      type: string(30)
    contact_email:
      type: string(255)
    latitude:
      type: string(255)
      notnull: true
    longitude:
      type: string(255)
      notnull: true
    building:
      type: string(100)
      notnull: true
    story:
      type: text
    mmi:
      type: float
    distance_from_epicentre:
      type: float
  relations:
    Earthquake:
      local: earthquake_id
      foreign: id
      foreignAlias: Reports

Damage:
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer
      notnull: true
      unique: true
      primary: true
    report_id:
      type: integer
      notnull: true
    damage:
      type: enum
      values: ['NONE','HAIRLINE_CRACKS','CRACKED_WINDOW','SOME_LARGE_WALL_CRACKS','MANY_LARGE_WALL_CRACKS','TILES_FELL','CHIMNEY_CRACKS','BROKEN_WINDOWS','MASONRY_FELL','OLD_CHIMNEY_FELL','NEW_CHIMNEY_FELL','WALL_COLLAPSED','ADDITION_SEPARATED','BUILDING_MOVED']
      notnull: true
  relations:
    Report:
      local: report_id
      foreign: id
      foreignAlias: Damages