<?php

/**
 * BaseDamage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $report_id
 * @property enum $damage
 * @property Report $Report
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method integer getReportId()  Returns the current record's "report_id" value
 * @method enum    getDamage()    Returns the current record's "damage" value
 * @method Report  getReport()    Returns the current record's "Report" value
 * @method Damage  setId()        Sets the current record's "id" value
 * @method Damage  setReportId()  Sets the current record's "report_id" value
 * @method Damage  setDamage()    Sets the current record's "damage" value
 * @method Damage  setReport()    Sets the current record's "Report" value
 * 
 * @package    quakefelt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDamage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('damage');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unique' => true,
             'primary' => true,
             ));
        $this->hasColumn('report_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('damage', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'NONE',
              1 => 'HAIRLINE_CRACKS',
              2 => 'CRACKED_WINDOW',
              3 => 'SOME_LARGE_WALL_CRACKS',
              4 => 'MANY_LARGE_WALL_CRACKS',
              5 => 'TILES_FELL',
              6 => 'CHIMNEY_CRACKS',
              7 => 'BROKEN_WINDOWS',
              8 => 'MASONRY_FELL',
              9 => 'OLD_CHIMNEY_FELL',
              10 => 'NEW_CHIMNEY_FELL',
              11 => 'WALL_COLLAPSED',
              12 => 'ADDITION_SEPARATED',
              13 => 'BUILDING_MOVED',
             ),
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Report', array(
             'local' => 'report_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}