<?php

/**
 * BaseEarthquake
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property float $magnitude
 * @property string $link
 * @property string $description
 * @property float $latitude
 * @property float $longitude
 * @property datetime $time_of_quake
 * @property float $depth
 * @property Doctrine_Collection $Reports
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method float               getMagnitude()     Returns the current record's "magnitude" value
 * @method string              getLink()          Returns the current record's "link" value
 * @method string              getDescription()   Returns the current record's "description" value
 * @method float               getLatitude()      Returns the current record's "latitude" value
 * @method float               getLongitude()     Returns the current record's "longitude" value
 * @method datetime            getTimeOfQuake()   Returns the current record's "time_of_quake" value
 * @method float               getDepth()         Returns the current record's "depth" value
 * @method Doctrine_Collection getReports()       Returns the current record's "Reports" collection
 * @method Earthquake          setId()            Sets the current record's "id" value
 * @method Earthquake          setMagnitude()     Sets the current record's "magnitude" value
 * @method Earthquake          setLink()          Sets the current record's "link" value
 * @method Earthquake          setDescription()   Sets the current record's "description" value
 * @method Earthquake          setLatitude()      Sets the current record's "latitude" value
 * @method Earthquake          setLongitude()     Sets the current record's "longitude" value
 * @method Earthquake          setTimeOfQuake()   Sets the current record's "time_of_quake" value
 * @method Earthquake          setDepth()         Sets the current record's "depth" value
 * @method Earthquake          setReports()       Sets the current record's "Reports" collection
 * 
 * @package    quakefelt
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEarthquake extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('earthquake');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unique' => true,
             'primary' => true,
             ));
        $this->hasColumn('magnitude', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('link', 'string', 400, array(
             'type' => 'string',
             'length' => 400,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('latitude', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('longitude', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('time_of_quake', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('depth', 'float', null, array(
             'type' => 'float',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Report as Reports', array(
             'local' => 'id',
             'foreign' => 'earthquake_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}