<?php

/**
 * DamageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DamageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DamageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Damage');
    }
}