# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        QuakeFelt Mobile
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    
                  - http://code.jquery.com/mobile/1.0a4.1/jquery.mobile-1.0a4.1.min.css
                  - style.css?v=1

  javascripts:    
                  - script.js
				  - location.js
                  - libs/latlon.js

                  - http://maps.google.com/maps/api/js?sensor=true
                  - libs/jquery.mobile-1.0a4.1.min.js
                  - mylibs/helper.js
                  
  has_layout:     true
  layout:         layout
